apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kamolhasan/argo-application.git
    targetRevision: HEAD
    path: applications
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true # Automatically delete resources that are no longer in Git
      selfHeal: true # Automatically update resources that have drifted from Git
      allowEmpty: false # Do not allow an empty spec
    syncOptions:
      - Validate=false
      - Prune=true
    retry: # Retry failed syncs
      limit: 3
      backoff:
        duration: 30
        factor: 2
        maxDuration: 300
